name: fitness
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  fl_chart: ^0.63.0
  http: ^1.2.2
  fluttertoast: ^8.0.8
  simple_animation_progress_bar: ^1.6.0
  dotted_dashed_line: ^0.0.3
  simple_circular_progress_bar: ^1.0.2
  animated_toggle_switch: ^0.6.2
  readmore: ^2.1.0
  calendar_agenda:
    path: dev_lib/calendar_agenda/
  intl: ^0.18.1

dependency_overrides: 
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/img/activity_tab.png
    - assets/img/activity_tab_select.png
    - assets/img/alaarm.png
    - assets/img/apple_pie.png
    - assets/img/ArrowLeft.png
    - assets/img/ArrowRight.png
    - assets/img/baking_soda.png
    - assets/img/barbell.png
    - assets/img/bed.png
    - assets/img/Bed_Add.png
    - assets/img/bell.png
    - assets/img/bg_dots.png
    - assets/img/black_btn.png
    - assets/img/bottle.png
    - assets/img/burn.png
    - assets/img/camera_tab.png
    - assets/img/camera_tab_select.png
    - assets/img/carbo.png
    - assets/img/chicken.png
    - assets/img/choose_workout.png
    - assets/img/closed_btn.png
    - assets/img/coffee.png
    - assets/img/complete_profile.png
    - assets/img/complete_workout.png
    - assets/img/c_1.png
    - assets/img/c_2.png
    - assets/img/c_3.png
    - assets/img/c_4.png
    - assets/img/date.png
    - assets/img/date_notifi.png
    - assets/img/detail_top.png
    - assets/img/difficulity.png
    - assets/img/egg.png
    - assets/img/eggs.png
    - assets/img/email.png
    - assets/img/facebook.png
    - assets/img/fav.png
    - assets/img/Filter.png
    - assets/img/flour.png
    - assets/img/foot.png
    - assets/img/f_1.png
    - assets/img/f_2.png
    - assets/img/gender.png
    - assets/img/glass-of-milk 1.png
    - assets/img/goal_1.png
    - assets/img/goal_2.png
    - assets/img/goal_3.png
    - assets/img/google.png
    - assets/img/hight.png
    - assets/img/home_tab.png
    - assets/img/home_tab_select.png
    - assets/img/honey_pan.png
    - assets/img/HoursTime.png
    - assets/img/img_1.png
    - assets/img/img_2.png
    - assets/img/lock.png
    - assets/img/more_btn.png
    - assets/img/More_V.png
    - assets/img/m_1.png
    - assets/img/m_2.png
    - assets/img/m_3.png
    - assets/img/m_4.png
    - assets/img/next_go.png
    - assets/img/next_icon.png
    - assets/img/nigiri.png
    - assets/img/notification_active.png
    - assets/img/no_bell.png
    - assets/img/oatmeal.png
    - assets/img/on_1.png
    - assets/img/on_2.png
    - assets/img/on_3.png
    - assets/img/on_4.png
    - assets/img/orange.png
    - assets/img/pancake_1.png
    - assets/img/pic_4.png
    - assets/img/pic_5.png
    - assets/img/Play.png
    - assets/img/pp_1.png
    - assets/img/pp_2.png
    - assets/img/pp_3.png
    - assets/img/pp_4.png
    - assets/img/pp_5.png
    - assets/img/pp_6.png
    - assets/img/pp_7.png
    - assets/img/pp_8.png
    - assets/img/profile_tab.png
    - assets/img/profile_tab_select.png
    - assets/img/progress_each_photo.png
    - assets/img/proteins.png
    - assets/img/p_achi.png
    - assets/img/p_activity.png
    - assets/img/p_contact.png
    - assets/img/p_next.png
    - assets/img/p_notification.png
    - assets/img/p_personal.png
    - assets/img/p_privacy.png
    - assets/img/p_setting.png
    - assets/img/p_workout.png
    - assets/img/rd_1.png
    - assets/img/Repeat.png
    - assets/img/repetitions.png
    - assets/img/salad.png
    - assets/img/search.png
    - assets/img/share.png
    - assets/img/show_password.png
    - assets/img/skipping_rope.png
    - assets/img/SleepGraph.png
    - assets/img/sleep_grap.png
    - assets/img/sleep_schedule.png
    - assets/img/sub_menu.png
    - assets/img/sugar.png
    - assets/img/time.png
    - assets/img/time_workout.png
    - assets/img/u1.png
    - assets/img/u2.png
    - assets/img/user_text.png
    - assets/img/Vibrate.png
    - assets/img/video_temp.png
    - assets/img/water.png
    - assets/img/weight.png
    - assets/img/welcome.png
    - assets/img/what_1.png
    - assets/img/what_2.png
    - assets/img/what_3.png
    - assets/img/Workout1.png
    - assets/img/Workout2.png
    - assets/img/Workout3.png

    - assets/font/Poppins-Bold.ttf
    - assets/font/Poppins-Medium.ttf
    - assets/font/Poppins-Regular.ttf
    - assets/img/logo.png
